name: Deploy

on:
  push:
    branches: [main, dev]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'dev' && 'github-pages-dev' || 'github-pages' }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website
          publish_branch: gh-pages
          destination_dir: ${{ github.ref_name == 'dev' && 'dev' || '.' }}
